### ISSUE TITLE
Make error  on rtl8188eus file

### ISSUE THREAD

**Issue by junnu-junaid** [aircrack-ng/rtl8188eus#106]
During make make time im getting error as
/Lib/modules/5.9.0-kali-amd64/build: no such file or directory . Stop
Make file : 2059 : modules error 2 
... 
Even though i have installed all build essential generic but still im facing the same errors.

**Comment by SmillerMP** [comment]
You have to install linux headers, search others issues about make error 2

See that issue https://github.com/aircrack-ng/rtl8188eus/issues/64

**Comment by junnu-junaid** [comment]
I have installed but still it says the same

**Comment by MrEngman** [comment]
The build error is because a symbolic link to you kernel source is missing.

You need to add the symbolic link using command like below to point to where your kernel source directory is.

sudo ln -s /home/kernel/source  /lib/modules/$(uname -r)/build
