### ISSUE TITLE
Not working in Fedora 33, kernel 5.10.7

### ISSUE THREAD

**Issue by mayconcancini** [aircrack-ng/rtl8188eus#107]
After upgrade from kernel 5.10.6 to 5.10.7 in Fedora 33, and again make && sudo make install, this driver stopped working.

$ lsusb
...
Bus 001 Device 003: ID 0bda:8179 Realtek Semiconductor Corp. RTL8188EUS 802.11n Wireless Network Adapter
...

**Comment by rfm83** [comment]
Same issue for rtl8821ce wireless driver.

**Comment by mayconcancini** [comment]
After upgrading to the 5.10.8 kernel, the driver returned to normal operation.

**Comment by galda01** [comment]
Same issue. 

Kernel: 5.10.11-200.fc33.x86_64

It was working prior to the upgrade from Fedora 32 to Fedora 33. 

Reproduce:
- ifconfig wlp0s20f3 down
- airodump-ng wlp0s20f3
- <can't see any wifi traffic>

Also, at this point, the system can't get WIFI up again. I'm sure there's a way but i haven't figure it out yet. Needs a reboot until i do figure it out.
