### ISSUE TITLE
last driver installing usb not working

### ISSUE THREAD

**Issue by Saliver7Sky** [aircrack-ng/rtl8188eus#11]
root@SliFer:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 13d3:3491 IMC Networks 
Bus 001 Device 003: ID 0bda:57e6 Realtek Semiconductor Corp. USB2.0 VGA UVC WebCam
Bus 001 Device 002: ID 2357:010c TP-Link TL-WN722N v2
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
root@SliFer:~# airmon-ng

PHY	Interface	Driver		Chipset

phy0	wlan0		ath10k_pci	Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)

**Comment by kimocoder** [comment]
Issue resolved. Use "git pull" to update or git clone to clone again, then compile/build/install.
Thanks!
