### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by ibnuvboys** [aircrack-ng/rtl8188eus#114]
please help me
kali 2020.4
5.10.0-kali3-amd64

![Screenshot from 2021-03-08 12-23-12](https://user-images.githubusercontent.com/80239492/110278684-98982e00-7fcf-11eb-95af-483fababeb57.png)

**Comment by KokoseiJ** [comment]
haven't tested it, but I made a quick dirty patch:
[osdep_service_5.10_patch.diff.zip](https://github.com/aircrack-ng/rtl8188eus/files/6105974/osdep_service_5.10_patch.diff.zip)
should be applied to `os_dep/osdep_service.c`. This patch was made for [`v5.7.6.1`](https://github.com/aircrack-ng/rtl8188eus/tree/v5.7.6.1) branch.
I can't guarantee that it works without any problems, I just made this patch based on patches applied in other projects. at least it boots.
Can any of the contributors confirm this patch?
