### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by Shr1mps** [aircrack-ng/rtl8188eus#115]
i was following the instructions an this happened, im in a vm dont know if its relevant to know

![imagen](https://user-images.githubusercontent.com/69219668/111799130-7f359280-88a9-11eb-85b6-ff940ccea12f.png)

**Comment by SmillerMP** [comment]
You need to install linux headers

**Comment by SmillerMP** [comment]
Try with 
```
sudo apt-get install linux-headers-$(uname -r)
```

And post the results

**Comment by Shr1mps** [comment]
installed them but then i got this

![imagen](https://user-images.githubusercontent.com/69219668/111802933-4e575c80-88ad-11eb-8b55-89a20fd60c9f.png)

**Comment by SmillerMP** [comment]
Try with
```
sudo apt-get install bc
```

**Comment by Shr1mps** [comment]
i read the solution to the issue #114  and it worked, thank any way
