### ISSUE TITLE
Unable to change mac

### ISSUE THREAD

**Issue by BeingDatta** [aircrack-ng/rtl8188eus#12]
Installed this driver correctly but unable to change mac

**Comment by kimocoder** [comment]
Will take a look at this shortly. I'll get back.

**Comment by BeingDatta** [comment]
Its solved but can you implement this in your driver
1. **sudo su**
2. **echo "options r8188eu rtm_initmac=11:22:33:aa:bb:cc" > /etc/modprobe.d/r8188eu.conf** (it will create a r8188eu.conf file inside /etc/modprobe.d folder
3. **modprobe -rv r8188eu** (to unload module)
    **modprobe -v r8188eu** (to reload it)
Dont need restart, after this just attach wifi and pass

i**fconfig wlan0 down
macchanger -r wlan0
ifconfig wlan0 up**

Its tested worked for me. Anyway Thank You for such magnificent driver.

Regards

**Comment by kimocoder** [comment]
You know the "r8188eu" is the kernel driver, right? our module is named "8188eu", and the r8188eu should be blacklisted.
