### ISSUE TITLE
Black-list the Driver

### ISSUE THREAD

**Issue by Neo-vortex** [aircrack-ng/rtl8188eus#14]
I had to change  :
"echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"
to:
"echo "blacklist r8188eu" > "/etc/modprobe.d/realtek.conf"
to work on my machine.
my system : 
"Linux Lab 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux"

**Comment by kimocoder** [comment]
Done

**Comment by ghost** [comment]
> I had to change : "echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf" to: "echo "blacklist r8188eu" > "/etc/modprobe.d/realtek.conf" to work on my machine. my system : "Linux Lab 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux"

how to whitelist :
"echo "blacklist r8188eu.ko" > "/etc/modprobe.d/realtek.conf"
to:
"echo "blacklist r8188eu" > "/etc/modprobe.d/realtek.conf"
to work on my machine.

**Comment by ghost** [comment]
please! help me to white list my WIFI adapter.? in kali linux.
