### ISSUE TITLE
Nethunter-kernal-headers

### ISSUE THREAD

**Issue by ShishirKhanal001** [aircrack-ng/rtl8188eus#142]
{
cd [your kernel source directory]
make module_prepare
make modules_install INSTALL_MOD_PATH=../
}

I am unable to build nethunter #kernal headers , can it be little bit more understandable, like am using 

Linux kali 4.14.117-Draco-Re4son #1 SMP Wed Sep 8 13:14:39 AEST 2021 aarch64

What can I do for this kernal to support rtl8188eus

**Comment by lucky-zwx** [comment]
我遇到了和你一样的问题，请问你解决了么？
