### ISSUE TITLE
Error during make install

### ISSUE THREAD

**Issue by 10maurycy10** [aircrack-ng/rtl8188eus#145]
When I run ```make install``` it gets stuck on depmod.

after a while it prints out pages of errors:

sample:
````depmod: ERROR: openat(4999, module, O_RDONLY): Too many open files
depmod: ERROR: openat(4999, fs, O_RDONLY): Too many open files
depmod: ERROR: openat(4999, buildtime, O_RDONLY): Too many open files
depmod: ERROR: openat(4999, rt2800pci, O_RDONLY): Too many open files
depmod: ERROR: openat(4999, plx, O_RDONLY): Too many open files
depmod: ERROR: openat(4999, davicom, O_RDONLY): Too many open files
````

uname -a ```Linux kitty 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux```

I ran ```ulimit -n 4000``` as root and that simply increased the time to error.

**Comment by shashankx86** [comment]
use this https://github.com/drygdryg/rtl8188eus
