### ISSUE TITLE
driver dosent get compiled 

### ISSUE THREAD

**Issue by Om-Suryawanshi** [aircrack-ng/rtl8188eus#155]
i use latest version of kali bur it still dosent work i am not any developer or expert on kali but if i would get some help i would be apreciated 

sudo make

cut: /etc/redhat-release: No such file or directory
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.15.0-kali2-amd64/build M=/home/kali/rtl8188eus  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.0-kali2-amd64'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.2.0-12) 11.2.0
  You are using:           gcc-11 (Debian 11.2.0-13) 11.2.0
cut: /etc/redhat-release: No such file or directory
  CC [M]  /home/kali/rtl8188eus/core/rtw_br_ext.o
/home/kali/rtl8188eus/core/rtw_br_ext.c:20:18: fatal error: net/ipx.h: No such file or directory
   20 |         #include <net/ipx.h>
      |                  ^~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.15.0-kali2-common/scripts/Makefile.build:282: /home/kali/rtl8188eus/core/rtw_br_ext.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.15.0-kali2-common/Makefile:1892: /home/kali/rtl8188eus] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-kali2-amd64'
make: *** [Makefile:2062: modules] Error 2

**Comment by dmijsMe71274** [comment]
Hello, we have the same problem, i sympathize with you. I destroyed, rebuilt my VM many times to know if it's the same error in kernel 5.15.0-kali2-amd64... even downgraded to 5.10.0-kali9-amd64... but no success. Also tried version 5.3. & 5.7...
this mostly caught my attention:

"The kernel was built by: gcc-11 (Debian 11.2.0-12) 11.2.0
You are using: gcc-11 (Debian 11.2.0-13) 11.2.0
cut: /etc/redhat-release: No such file or directory.."

Hope some good soul knows a work around this. :)

Now still experimenting and reading troubleshooting issues about this rtl8188eus. I use TP-Link  TL-WN722N V2/V3 wifi adapter.

**Comment by gudarzi** [comment]
use this: https://github.com/aircrack-ng/rtl8188eus/pull/152

> Hello, we have the same problem, i sympathize with you. I destroyed, rebuilt my VM many times to know if it's the same error in kernel 5.15.0-kali2-amd64... even downgraded to 5.10.0-kali9-amd64... but no success. Also tried version 5.3. & 5.7... this mostly caught my attention:
> 
> "The kernel was built by: gcc-11 (Debian 11.2.0-12) 11.2.0 You are using: gcc-11 (Debian 11.2.0-13) 11.2.0 cut: /etc/redhat-release: No such file or directory.."
> 
> Hope some good soul knows a work around this. :)
> 
> Now still experimenting and reading troubleshooting issues about this rtl8188eus. I use TP-Link TL-WN722N V2/V3 wifi adapter.

Also, do a `sudo make clean` before compiling again

**Comment by ashishkumarjaiswal** [comment]
same problem

**Comment by chShiraz** [comment]
I am facing the same issue, hope someone can help us out with this.

**Comment by megar9876** [comment]
sudo apt update
sudo apt install bc
sudo rmmod r8188eu.ko
git clone https://github.com/isqad/rtl8188eus.git
cd rtl8188eus
sudo -i
echo "blacklist r8188eu" > "/etc/modprobe.d/realtek.conf"
exit
make
sudo make install
sudo modprobe 8188eu

Works for me finally

**Comment by shashankx86** [comment]
use this https://github.com/drygdryg/rtl8188eus
