### ISSUE TITLE
pahole-flags.sh: not found -- when i do "make"

### ISSUE THREAD

**Issue by noyumeAkira** [aircrack-ng/rtl8188eus#172]
Hello everyone, i have a issue with kernel 5.16.0 on parrotOS when i do make:
`/bin/sh: 1: /usr/src/linux-headers-5.16.0-12parrot1-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-12parrot1-common/scripts/pahole-flags.sh: not found
`
![Captura de pantalla -2022-03-23 19-32-30](https://user-images.githubusercontent.com/102180277/159807080-f2ac9f9f-cd27-4627-92d6-8ce0f7ad24dd.png)

any ideas?

**Comment by napolegend** [comment]
How u solved it
