### ISSUE TITLE
error in sudo make

### ISSUE THREAD

**Issue by AfridiEshrak** [aircrack-ng/rtl8188eus#182]
![ERROR](https://user-images.githubusercontent.com/37280786/176486547-7e287601-51df-4565-8eda-61e7fb20d0b4.png)

**Comment by quickreflex** [comment]
[Have you tried the driver from the previous issues?](https://github.com/aircrack-ng/rtl8188eus/issues/181)

**Comment by AfridiEshrak** [comment]
> [Have you tried the driver from the previous issues?](https://github.com/aircrack-ng/rtl8188eus/issues/181)

Problem solved! Thanks.
