### ISSUE TITLE
make error in kali linux kernel 5.18.0

### ISSUE THREAD

**Issue by cocoth** [aircrack-ng/rtl8188eus#189]
when i try to make this module in my kali linux i found something weird
 this is the command i use
`make`

> make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.18.0-kali2-amd64/build M=/home/sysx/Desktop/rtl8188eus  modules
> make[1]: Entering directory '/usr/src/linux-headers-5.18.0-kali2-amd64'
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_cmd.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_security.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_debug.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_io.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_ioctl_query.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_ioctl_set.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_ieee80211.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_mlme.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_mlme_ext.o
> /home/sysx/Desktop/rtl8188eus/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
> /home/sysx/Desktop/rtl8188eus/core/rtw_mlme_ext.c:1838:25: warning: attribute ‘fallthrough’ not preceding a case label or default label
>  1838 |                         __attribute__ ((__fallthrough__));
>       |                         ^~~~~~~~~~~~~
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_mi.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_wlan_util.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_vht.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_pwrctrl.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_rf.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_recv.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_sta_mgt.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_ap.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/mesh/rtw_mesh.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/mesh/rtw_mesh_pathtbl.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/mesh/rtw_mesh_hwmp.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_xmit.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_p2p.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_rson.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_tdls.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_br_ext.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_iol.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_sreset.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_btcoex_wifionly.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_btcoex.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_beamforming.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_odm.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_rm.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/rtw_rm_fsm.o
>   CC [M]  /home/sysx/Desktop/rtl8188eus/core/efuse/rtw_efuse.o
> /home/sysx/Desktop/rtl8188eus/core/efuse/rtw_efuse.c: In function ‘rtw_efuse_analyze’:
> /home/sysx/Desktop/rtl8188eus/core/efuse/rtw_efuse.c:714:17: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
>   714 |                 if (i % 16 == 0)
>       |                 ^~
> In file included from /home/sysx/Desktop/rtl8188eus/include/drv_types.h:59,
>                  from /home/sysx/Desktop/rtl8188eus/core/efuse/rtw_efuse.c:17:
> /home/sysx/Desktop/rtl8188eus/include/rtw_debug.h:194:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
>   194 |         do {\
>       |         ^~
> /home/sysx/Desktop/rtl8188eus/core/efuse/rtw_efuse.c:716:25: note: in expansion of macro ‘_RTW_PRINT_SEL’
>   716 |                         _RTW_PRINT_SEL(RTW_DBGDUMP, "%02X%s"
>       |                         ^~~~~~~~~~~~~~
>   CC [M]  /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.o
> /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.c: In function ‘thread_exit’:
> /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.c:1271:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
>  1271 |         complete_and_exit(comp, 0);
>       |         ^~~~~~~~~~~~~~~~~
> /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.c: In function ‘rtw_change_ifname’:
> /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.c:2450:28: warning: passing argument 1 of ‘_rtw_memcpy’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>  2450 |         _rtw_memcpy(pnetdev->dev_addr, adapter_mac_addr(padapter), ETH_ALEN);
>       |                     ~~~~~~~^~~~~~~~~~
> /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.c:899:24: note: expected ‘void *’ but argument is of type ‘const unsigned char *’
>   899 | void _rtw_memcpy(void *dst, const void *src, u32 sz)
>       |                  ~~~~~~^~~
> cc1: some warnings being treated as errors
> make[2]: *** [/usr/src/linux-headers-5.18.0-kali2-common/scripts/Makefile.build:293: /home/sysx/Desktop/rtl8188eus/os_dep/osdep_service.o] Error 1
> make[1]: *** [/usr/src/linux-headers-5.18.0-kali2-common/Makefile:1858: /home/sysx/Desktop/rtl8188eus] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.18.0-kali2-amd64'
> make: *** [Makefile:2058: modules] Error 2
>

**Comment by quickreflex** [comment]
There is a solution to the problem. Read the other issues below where the patched driver file is.

**Comment by cocoth** [comment]
> There is a solution to the problem. Read the other issues below where the patched driver file is.

yes, I've found the driver for kernel 5.18.x
https://github.com/aircrack-ng/rtl8188eus/files/8977331/rtl8188eus_new.tar.gz

thanks
