### ISSUE TITLE
Compile Error on kernel 5.18

### ISSUE THREAD

**Issue by ghost** [aircrack-ng/rtl8188eus#195]
trying to compile on kernel 5.18.. parrot os but i get this error 

https://pastebin.pl/view/c3490a0d

it only works on kernel 5.15

**Comment by SimplyCEO** [comment]
Duplicate of https://github.com/aircrack-ng/rtl8188eus/issues/187
Honestly... until no PRs get tested by OP, this error will be very common.

**Comment by ghost** [comment]
what is PRs

**Comment by SimplyCEO** [comment]
@voldmort21 [Pull Request](https://github.com/aircrack-ng/rtl8188eus/pulls)
