### ISSUE TITLE
Compile error with 5.4 kernel

### ISSUE THREAD

**Issue by MrR0b0X** [aircrack-ng/rtl8188eus#217]
@kimocoder  this problem on samsung kernel 5.4, happened on rtl8188eus too
i tried to change <> to "" or add include dir in Makefile, also tried to build them as module but nothing useful
![Screenshot_٢٠٢٢١٢٠٢-١٢٣٣٤٣_Termux](https://user-images.githubusercontent.com/35136385/205510345-a2e3883c-357c-4eb9-be00-b600b1d725ce.jpg)

**Comment by AWM006** [comment]
need to modify the driver's code

**Comment by MrR0b0X** [comment]
> need to modify the driver's code

you're replying to an old topic, i made a fix for it already: https://github.com/aircrack-ng/rtl8188eus/commit/3a4ce2bde940b02a476577acf87087dacbffe34c
