### ISSUE TITLE
drv_types.h: No such file or directory

### ISSUE THREAD

**Issue by LoaiEsam37** [aircrack-ng/rtl8188eus#221]
```make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.16.0-kali7-amd64/build M=/home/loai/rtl8188eus  modules
make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-11 (Debian 11.2.0-19) 11.2.0
  You are using:           gcc-11 (Debian 11.3.0-8) 11.3.0
/bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
  CC [M]  /home/loai/rtl8188eus/core/rtw_cmd.o
/home/loai/rtl8188eus/core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
   17 | #include <drv_types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/usr/src/linux-headers-5.16.0-kali7-common/scripts/Makefile.build:292: /home/loai/rtl8188eus/core/rtw_cmd.o] Error 1
make[1]: *** [/usr/src/linux-headers-5.16.0-kali7-common/Makefile:1870: /home/loai/rtl8188eus] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
make: *** [Makefile:2062: modules] Error 2
```

Can you help me please solve this problem ?

**Comment by MrR0b0X** [comment]
> ```makefile
> make[1]: Entering directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
> /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
> /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
> warning: the compiler differs from the one used to build the kernel
>   The kernel was built by: gcc-11 (Debian 11.2.0-19) 11.2.0
>   You are using:           gcc-11 (Debian 11.3.0-8) 11.3.0
> /bin/sh: 1: /usr/src/linux-headers-5.16.0-kali7-common/scripts/pahole-flags.sh: not found
>   CC [M]  /home/loai/rtl8188eus/core/rtw_cmd.o
> /home/loai/rtl8188eus/core/rtw_cmd.c:17:10: fatal error: drv_types.h: No such file or directory
>    17 | #include <drv_types.h>
>       |          ^~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [/usr/src/linux-headers-5.16.0-kali7-common/scripts/Makefile.build:292: /home/loai/rtl8188eus/core/rtw_cmd.o] Error 1
> make[1]: *** [/usr/src/linux-headers-5.16.0-kali7-common/Makefile:1870: /home/loai/rtl8188eus] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.16.0-kali7-amd64'
> make: *** [Makefile:2062: modules] Error 2
> ```
> 
> Can you help me please solve this problem ?

https://github.com/aircrack-ng/rtl8188eus/issues/220#issuecomment-1358935037
