### ISSUE TITLE
A request 

### ISSUE THREAD

**Issue by Masrkai** [aircrack-ng/rtl8188eus#230]
IN EVERY KERNEL UPDATE SOMETHING GETS MESSEE UP
can you please make this thing a little module or extension in the code that we can write or generate or give any sort of explanation to this.. it's really really frustrating.. in Egypt we don't have except this specific card tbh.. so it would be great just to try to solve this on our own on every kernel update
While I do really respect your work because you are the ones who got me in cyber security in the first place and made me find my passion.. but yeah that..that issue is getting on my nerve please..
Make an explanation for this 
And If you can.. and it would be great make that thing that gets messed up generatable.. so we can install it in a better way in future...  Thanks for reading 💙

**Comment by aircrack-ng** [comment]
That is not possible: things change in the kernel. However, it eventually gets fixed. A solution for you is to use a regular distribution like a stable Debian or Ubuntu LTS, and that is likely not gonna be a problem.

If you need things fixed right away, feel free to pay someone to take care of it, or provide a patch.
