### ISSUE TITLE
TPLink driver rtl8188eus Installation isuue

### ISSUE THREAD

**Issue by Termin7** [aircrack-ng/rtl8188eus#245]
I was trying to install drivers for my TPlink WN722N adapter in KALI LINUX, Then I faced this issue
Kali VM version : 2022

Error : rtl8188eus/os_dep/osdep_service.c:2582:16: error: implicit declaration of function ‘prandom_u32’; did you mean ‘prandom_u32_max’? [-Werror=implicit-function-declaration]
 2582 |         return prandom_u32();

**Comment by hamzaplojovic** [comment]
Could you please explain how did you solve this
