### ISSUE TITLE
make error on 6.4.0-kali3-arm64

### ISSUE THREAD

**Issue by skyper-cz** [aircrack-ng/rtl8188eus#262]
Hi, I wanted to install these drivers on my virtual machine which connects to my usb dongle.
However Im getting following error.

![Screenshot 2023-09-11 at 19 02 51](https://github.com/aircrack-ng/rtl8188eus/assets/62872636/3282356b-8768-4589-8367-dd189987e07f)
Any idea how to solve it. It might me the ARM64 issue.

**Comment by gglluukk** [comment]
Hi,

There are no issues for using driver under ARM64 (I use https://github.com/utmapp/UTM/ for Apple M1).

Try:
```
apt --yes install build-essential linux-headers-`uname -r` bc
```

**Comment by skyper-cz** [comment]
It started working but now I got following error:

<img width="1319" alt="Screenshot 2023-09-11 at 22 44 01" src="https://github.com/aircrack-ng/rtl8188eus/assets/62872636/1f5cb8a4-877e-420b-a27f-ac747477fa24">

**Comment by gglluukk** [comment]
same issue was described, read it here: https://github.com/aircrack-ng/rtl8188eus/issues/256

**Comment by skyper-cz** [comment]
Thanks, using your variant it is working now.
