### ISSUE TITLE
Arch, Kernel v6.7 make error

### ISSUE THREAD

**Issue by G0ld3nDr4g0n3301** [aircrack-ng/rtl8188eus#278]
Got an error, during compilation of os_dep/linux/ioctl_cfg80211.o  . I'm building https://github.com/gglluukk/rtl8188eus as you suggested in another issue. 
![Screenshot_20240122_225419](https://github.com/aircrack-ng/rtl8188eus/assets/91593551/94f52269-1a47-448f-bd62-12b02e944711)
![Screenshot_20240122_225335](https://github.com/aircrack-ng/rtl8188eus/assets/91593551/b90debbd-a714-49b5-9a84-fcfe055e4cbb)

**Comment by gglluukk** [comment]
Hi,
I've patched driver to support kernel 6.7, so clone again and recompile

**Comment by G0ld3nDr4g0n3301** [comment]
Thank you very much! It works now.
