### ISSUE TITLE
warning: the compiler differs from the one used to build the kernel

### ISSUE THREAD

**Issue by diehard88** [aircrack-ng/rtl8188eus#307]
I recently upgraded from Linux Mint 21.3 to 22.   The kernel was also upgraded to Linux 6.8.

Now I´m getting this warning if I compile the rtl8188eus driver.

![compiler warning](https://github.com/user-attachments/assets/f9851511-4b05-4a03-827b-4bccd186e32d)

The linux headers are installed.

any ideas?

thank you.

**Comment by gglluukk** [comment]
it's ok, compilers' versions are same, only calling binaries are different

**Comment by diehard88** [comment]
> it's ok, compilers' versions are same, only calling binaries are different

understood.

before the upgrade, compilation would take several seconds and display a lot of messages during ´make´ and ´sudo make install´ and end successfully.

now it simply shows that warning, and nothing else.   

the ´sudo make install´ shows the following:    

![Screenshot from 2024-12-04 22-06-09](https://github.com/user-attachments/assets/2134a72f-9c63-4187-8298-a4c90b466870)


  
note:  I´m testing with two kernel versions:  6.8.0.47 and .49....

**Comment by diehard88** [comment]
I just realized that there is no problem.

I was using @gglluukk rtl8188eu fork to compile the drivers.
his version displays more info during compilation, while the original 8188eu is more succinct.

**Comment by gglluukk** [comment]
difference is that https://github.com/gglluukk/rtl8188eus supports 6.8 but pull requests have never been accepted
