### ISSUE TITLE
added kernel 5.6.0 patch

### ISSUE THREAD

**Issue by darkalexpp** [aircrack-ng/rtl8188eus#33]
patch for kernel 5.6

[patch_added_kernel_5.6.0.txt](https://github.com/aircrack-ng/rtl8188eus/files/4415493/patch_added_kernel_5.6.0.txt)

**Comment by niteshagrawal** [comment]
i am using kali 2020.1. since i am new to all these stuff. it will be very helpful if you can tell me how to use this patch. and it will be very helpful if you have any video tutorial regarding this.

**Comment by darkalexpp** [comment]
> i am using kali 2020.1. since i am new to all these stuff. it will be very helpful if you can tell me how to use this patch. and it will be very helpful if you have any video tutorial regarding this.

you need to clone this git, and then copy "patch_added_kernel_5.6.0.txt" into rtl8188eus folder. so open a terminal in this path and apply with:

git apply patch_added_kernel_5.6.0.txt

alfter you can compiling and install with
make && make install

**Comment by runlevel5** [comment]
LGTM +1

**Comment by darkalexpp** [comment]
> LGTM +1
> 
> @darkalexcpp Could you please submit a Pull Request?

yes. I already submitted a pull request

**Comment by runlevel5** [comment]
The PR was merged. Please feel free to close this issue.
