### ISSUE TITLE
Is it possible to enable LED on TL-WN722N

### ISSUE THREAD

**Issue by AngryPhantom** [aircrack-ng/rtl8188eus#48]
Sorry, guys, I have a little question: 
I see you can enable **LED indicator** with another driver [here](https://github.com/aircrack-ng/rtl8812au).

Is it possible to enable it on **TL-WN722N** ?

Thank you.

**Comment by SmillerMP** [comment]
I have the same question :) and thanks for this driver! I am so happy with the results with the TP-WN722N v3 ❤️

**Comment by TBM13** [comment]
If i remember correctly, you can enable the LED on `include/autoconf.h`, by uncommenting this line: `/* #define CONFIG_RTW_LED */`

**Comment by AngryPhantom** [comment]
@TBM13 Oh, thank you very much. Will try it today. Cheers!
