### ISSUE TITLE
Iwconfig wlan0 mode monitor issue TL-WN722N

### ISSUE THREAD

**Issue by vytatuas** [aircrack-ng/rtl8188eus#52]
![wlan](https://user-images.githubusercontent.com/66017856/83031182-f0ffcf80-a03c-11ea-82b9-c2e040278a84.jpg)

I try to do something about 5-6 hours but I cannot pass to monitor mode. Please help me.

**Comment by SmillerMP** [comment]
I think is because you are not super user 

Test with the command 
```
sudo iw dev wlan0 set type monitor
```

Or

Become on super user with the command
```
sudo su 
```

And the correct form tu put your adapter in monitor mode is with the command **iw dev <adaptername> set type monitor**

Read the documentation for more informacion

**Comment by BeingDatta** [comment]
use ip link and iw dev instead of ifconfig and iwconfig see the instructions.

Regards

**Comment by kimocoder** [comment]
iwconfig is deprecated. Read the docs before opening issue report.
