### ISSUE TITLE
Invalid module format

### ISSUE THREAD

**Issue by unwind0** [aircrack-ng/rtl8188eus#61]
I get this error when I try to load the kernel module:
```insmod: ERROR: could not insert module kernel/drivers/net/wireless/8188eu.ko: Invalid module format```

kernel:
```4.15.0-106-generic```

**Comment by Si-i3ima** [comment]
Check [this](https://unix.stackexchange.com/questions/170503/insmod-error-could-not-insert-module-8188eu-ko-invalid-module-format) out

**Comment by unwind0** [comment]
@Si-i3ima Recompiled the module and worked fine, Thanks!
