### ISSUE TITLE
v 7.6.1 shows nothing with airmon-ng

### ISSUE THREAD

**Issue by SmillerMP** [aircrack-ng/rtl8188eus#62]
I wanted to test version 7.6.1 and after installing it, it no longer finds anything with airmon-ng and it doesn't let me inject

I have tried Kali 2019.1 and Mint 18.3 and the same error.

My adapter is a TL-WN722N v3

Does anyone know something

**Comment by kimocoder** [comment]
Not maintained. Use v5.3.9.
