### ISSUE TITLE
Make Error: No rule to make target "arch//Makefile" 

### ISSUE THREAD

**Issue by xXAnToS12Xx** [aircrack-ng/rtl8188eus#65]
Title says everything:
![image](https://user-images.githubusercontent.com/20314571/86960916-950e8780-c160-11ea-8592-471fa27cfd91.png)

**Comment by kiostudio** [comment]
Facing the same issue here, anyone can help ? 
<img width="840" alt="Screenshot 2020-07-09 at 11 13 45 AM" src="https://user-images.githubusercontent.com/63901064/86992951-4c44e600-c1d5-11ea-94ca-37846ced8226.png">

**Comment by murprakoso** [comment]
![Screenshot_20200709_165733-cut](https://user-images.githubusercontent.com/45523845/87193245-7fe15680-c322-11ea-94c7-cbffc00f30c4.png)

same issue :(

**Comment by drygdryg** [comment]
Latest commit https://github.com/aircrack-ng/rtl8188eus/commit/180a406396ab753c1d41e1aa9180eb64cdba9724 breaks build on Arch Linux (x86_64) and Linux Mint (x86):
```
victor:~/git/rtl8188eus $ make -j3
make ARCH= CROSS_COMPILE= -C /lib/modules/5.7.7-arch1-1/build M=/home/victor/git/rtl8188eus  modules
make[1]: Entering directory «/usr/lib/modules/5.7.7-arch1-1/build»
Makefile:669: arch//Makefile: No such file or directory
make[1]: *** No rule to make target «arch//Makefile».  Stop.
make[1]: Leaving directory  «/usr/lib/modules/5.7.7-arch1-1/build»
make: *** [Makefile:2058: modules] Error 2
```

**Comment by kimocoder** [comment]
Fixed. git pull and build
