### ISSUE TITLE
TL-WN722N_V3.0 With RTL8188EUS chipset. It supports Monitor mode and packet injection  or not?!

### ISSUE THREAD

**Issue by zankoatzanko** [aircrack-ng/rtl8188eus#72]
Hello.
I had a question, I want to buy the **TL-WN722N_V3.0** wireless network card, which is from the **RTL8188EUS** chipset. I wanted to know if it really supports Monitor mode and packet injection  or not ??
Thanks a lot.

**Comment by SmillerMP** [comment]
Hi. I have the same version of adapter! And it works fantastic! 

It support monitor mode and frame injection very well!

**Comment by zankoatzanko** [comment]
> Hi @zankoatzanko I have the same version of adapter! And it works fantastic!
> 
> It support monitor mode and frame injection very well!

Thanks so much for the quick reply.

**Comment by resist15** [comment]
Does It Works With Fluxion Or Hostapd

**Comment by SmillerMP** [comment]
@resist15 I think that with fluxion it is not compatible and with hostapd yes but if you configure it correctly

**Comment by drygdryg** [comment]
@resist15 it works with fluxion well due to support AP and monitor modes.
