### ISSUE TITLE
SOLUTION: FOR EVERYONE GETTING "no such device (-19)"

### ISSUE THREAD

**Issue by murprakoso** [aircrack-ng/rtl8188eus#79]
FOR EVERYONE GETTING "no such device (-19)"

-> Reload the right driver manually:
1. (Stick Adapter in)
2. `sudo rmmod r8188eu.ko`
3. `sudo modprobe 8188eu`
4. Stick Adapter out and in again
5. `sudo airmon-ng check kill`
6. `sudo ip link set wlan0 down`
7. `sudo iw dev wlan0 set type monitor`

**Comment by kimocoder** [comment]
r8188eu is lwfinger driver (kernel inbuilt)
it has to be disabled / blacklisted in modprobe

**Comment by GetRektBoy724** [comment]
i already blacklist the lwfinger driver but it still says "no such device (-19)"
i dont have any errors at "make && make install" at all...
PLS HLP

**Comment by AssafCode** [comment]
Work for me. Thank you very very much!!
