### ISSUE TITLE
Permission Denied While Black-Listing

### ISSUE THREAD

**Issue by Abdullah-Sajjad026** [aircrack-ng/rtl8188eus#92]
sudo echo "blacklist r8188eu" >> "/etc/modprobe.d/realtek.conf"
bash: /etc/modprobe.d/realtek.conf: Permission denied

This is result. I don't know why I am getting this error. I am using Linux Mint 20 Cinnamon. Please help!

**Comment by CanadianTerror** [comment]
Me too, figure it out yet?

**Comment by Abdullah-Sajjad026** [comment]
> Me too, figure it out yet?

https://github.com/kelebek333/rtl8188fu

This worked for me. Try this. Maybe it works for you too.

**Comment by Abdullah-Sajjad026** [comment]
Closing this issue because my issue solved.
https://github.com/kelebek333/rtl8188fu

 These drivers worked for me and I can enjoy WiFi on my Linux System. Thanks Tober!

**Comment by drygdryg** [comment]
The right way:
`sudo sh -c 'echo "blacklist r8188eu" >> /etc/modprobe.d/realtek.conf'`
